lsp_error: output final newline
Unify lsp_debug() and lsp_error() in that both output a final newline.
This makes calling them less painfull, because no more need to remeber
which one doesn't need a final newline -- none of them does.

Signed-off-by: Dirk Gouders <dirk@gouders.net>