lsp_error: write \n to logfile as well
Commit 40a166646c2ef2c2 (lsp_error: output final newline) didn't
handle output to the logfile.

Fixes: 40a166646c2ef2c2 (lsp_error: output final newline)
Signed-off-by: Dirk Gouders <dirk@gouders.net>