lsp_error: do endwin() before printing error message
If curses has been initialized before an error occurs we need to call
endwin() before printing the error message.
Otherwise the message isn't visible.

Fixes #17

Signed-off-by: Dirk Gouders <dirk@gouders.net>